#!/bin/bash
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1980*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1981*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1982*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1983*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1984*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1985*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1986*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1987*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1988*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1989*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1990*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1991*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1992*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1993*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1994*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1995*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1996*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1997*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1998*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_1999*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_2000*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_2001*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_2002*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_2003*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_2004*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_2005*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_2006*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_2007*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_2008*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_2009*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_2010*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_2011*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_2012*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_2013*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_2014*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_2015*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_2016*
./spark-2.0.0/bin/spark-submit --class "tools.ClimaDateTempObj" --jars /root/spark-2.0.0/SciSpark.jar /root/ClimaDate/SimpleTaskM.jar  -14 35 hdfs://localhost:9000/user/tmaxData/Interim_mx2t_2017*